### PR TITLE
Remove callback on tween.stop unless jump is set

### PR DESCRIPTION
**Pull request by danro**
This will change `tween.stop` to behave more like `jQuery.stop`... the callback should be removed when `stop()` is called, unless jump to end is true. (Then the callback would fire right away)

### CODE REVIEW

**Comment by ded** [comment]
what's jQuery's usecase?

**Comment by danro** [comment]
Here's a quote from their `stop()` docs:

> When .stop() is called on an element, the currently-running animation (if any) is immediately stopped. If, for instance, an element is being hidden with .slideUp() when .stop() is called, the element will now still be displayed, but will be a fraction of its previous height. Callback functions are not called.

and...

> If the jumpToEnd property is provided with a value of true, the current animation stops, but the element is immediately given its target values for each CSS property. In our above .slideUp() example, the element would be immediately hidden. The callback function is then immediately called, if provided.

Also, from my previous experience with just about any AS3 tweening engine, when you stop a tween in progress- the callback should be ignored. Sort of like `setTimeout` and `clearTimeout` in javascript.

**Comment by danro** [comment]
If you're hesitant to change the way callbacks work with `tween.stop()` then perhaps morpheus needs a `tween.clear()` or something to make sure the callbacks don't fire?

**Comment by ded** [comment]
nah this is fine.

**Comment by ded** [comment]
i added tests after the merge and then published to npm

**Comment by danro** [comment]
sweet, glad I could help. this is a great script.

**Pull request merged**
