### PR TITLE
(webkit/Moz/O/ms)Transform support

### PR DESCRIPTION
**Pull request by cjc**
G'day, I took a stab at adding transform animation support. It ended up adding more code than I expected but it works pretty nicely across rotate/skew/translate/scale in IE9/FF/Webkit/Opera.

Any interest in merging this functionality?

### CODE REVIEW

**Comment by ded** [comment]
Hmmm... I _do_ have interest. I had this idea that I would create a better extension model, but i think this makes most sense. It's all just animations anyway. 

I'll have a look thru and possibly change some code styles

**Comment by ded** [comment]
cool. merged it in a local branch and made some style changes. i'll have to sort out the tests for IE6/8. I added [bowser](https://github.com/ded/bowser) in the meantime since i may just bypass the tests for those browsers.

Thanks again for this wonderful addition to Morpheus!

cheers,
Dustin

**Comment by cjc** [comment]
Awesome, thanks for merging (and for polishing those rough corners).

I realised this morning that I forgot one thing. In the raw morpheus example I set the initial transform before starting the animation with <code>element.style[morpheus.transform];morpheus(element,...);</code>, but when used with ender that property isn't visible.

The simplest solution would be to expose morpheus.transform as a global with the ender wrapper, allowing <code>$(element).css({$.morpheusTransform:'rotate(30deg'}).animate('transform':'rotate(40deg)')</code> 

Alternatively, I could add the 'browser specific transform property name' detection to Bonzo to allow <code>$(element).css('transform':'rotate(30deg)').animate('transform':'rotate(40deg)')</code>

Let me know if you have a preference and I'll chuck it in asap.

Cheers,
Cameron

**Comment by ded** [comment]
the 2nd is much, much more prefered and i think Bonzo users would dig it.

**Pull request merged**
