### PR TITLE
Added support for backgroundPosition in px an %

### PR DESCRIPTION
**Pull request by rogchap**
Includes tests and example.

Support for animating the background position seems to be lacking in a lot of javascript animation libraries; _background-position-x_ and _background-position-y_ can be used but is not supported in Opera or Firefox.

### CODE REVIEW

**Comment by ded** [comment]
great work! i'll pull it down and test it out myself

**Comment by ded** [comment]
heyo @rogchap . just checking back in on this. i'd like to get this background-position thing in. sorry for the long delay.

**Comment by rogchap** [comment]
Hey @ded, How did the testing go? Seems like a lifetime has passed :)

**Comment by stereokai** [comment]
@ded I'm wondering myself :)

**Comment by ded** [comment]
this is no longer merging. you want to have a look?

**Comment by stereokai** [comment]
The request is not mine, but maybe I can help. Are you getting an error or something?

**Pull request closed without merging**
